config/routes.rb
Rails.application.routes.draw do
  root to: 'musics#index'
  
  resources :musics do
    resources :posts
  end

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music.rb
class Music < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :music

  validates :content, presence: true

  def created_time
    created_at.strftime("%Y年%m月%d日　%-H時%-M分")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  def index
    @musics = Music.all
  end

  def new
    @music = Music.new
  end

  def create
    @music = Music.new(set_params)
    if @music.save!
      redirect_to musics_path
    else
      render 'new'
    end
  end

  def show
    @title = params[:title]
    @url = params[:url]

    @music = Music.find(params[:id])
    @posts = @music.posts.order(created_at: :desc).page(params[:page]).per(5)
    @post = @music.posts.build
    respond_to do |format|
      format.js{render :show} 
      format.html
    end    
  end

  def destroy
    @music = Music.find(params[:id])

  end

  private

  def set_params
    params.require(:music).permit(:title, :url, :image)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/index.html.erb
<p>Brilliant Blue</p>
<div class="video-wrap">
  <p>Brilliant Blue</p>
  <iframe width="1280" height="720" src="http://www9.nhk.or.jp/das/movie/D0002011/D0002011458_00000_V_000.mp4" frameborder="0" allowfullscreen></iframe>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BohemianApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/musics/index.html.erb
<h1 class="text-center">どの<span>OMOIDE IN IN MY HEAD</span>について語る？</h1>

<div class="music-index">
  <div class="row">
    <% @musics.each do |music| %>
      <div class="col-sm-6 col-md-4 music-col">
        <%= link_to music_path(music, title: music.title, url: music.url) do %>
          <div>
            <%= image_tag(music.image) %>
          </div>
          <div>
            <%= music.title %>
          </div>
          <hr>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/musics/new.html.erb
<h1 class="text-center">動画を登録</h1>

<div class="row justify-content-center">
  <div class="col-md-8 col-xs-8">
    <%= form_with(model: @music, local:true) do |f| %>
      <div class="form-group">
        <%= f.label :title, "タイトル" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :url, "動画のURL(embedの記載がある埋め込み用のURLを記載)" %>
        <%= f.text_field :url, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :image, "画像のURL" %>
        <%= f.text_field :image, class: "form-control" %>
      </div>
      <div class="form-group text-center">
        <%= f.submit "登録", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/musics/show.html.erb
<h1 class="text-center">この動画どう？</h1>

<div class="text-center">
  <iframe class="embed-responsive-item" id='iframe' width="560" height="315" 
    src="<%= @url %>"
    frameborder="0" 
    allowfullscreen>
  </iframe>
</div>

<form>
  <div class="form-group">
    <input type="text" class="form-control" id="chat-input" placeholder="何を思う？">
  </div>
  <div class="text-right">
    <button class="btn btn-primary btn-lg" id="chat-button">送信</button>
  </div>
</form>

<div hidden>
  <div id="music-id"><%= @music.id %></div>
</div>

<div id="posts" class="posts-block">
  <ul class="list-group">
    <%= render @posts %>
  </ul>
</div>

<div class="text-center loading-btn">
  <%= link_to_next_page @posts, 'もっと見る', remote: true, id: 'more_link' %>
</div>

app/views/musics/show.js.erb
<% @posts.each do |post| %>
  $("#posts").append("<%= escape_javascript(render partial: 'posts/post', locals: { post: post }) %>");
<% end %>
$("#more_link").replaceWith("<%= escape_javascript(link_to_next_page(@posts, 'もっと見る', remote: true, id: 'more_link')) %>");

app/views/posts/_post.html.erb
<% cache post do %>
  <li class="list-group-item">
    <h4><%= post.content %></h4>
    <div class="post-time">
      <%= post.created_time %>
    </div> 
  </li>
<% end %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/show.html.erb
show.html.erb